package com.tomiguntur.ProjectAkhir.News;

import android.content.Intent;
import android.os.Bundle;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import com.tomiguntur.ProjectAkhir.R;

import java.util.ArrayList;

public class NewsActivity extends AppCompatActivity {
    private RecyclerView recNews;
    private ArrayList<News> listNews;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_news);

        getSupportActionBar().hide();

        recNews = findViewById(R.id.rec_news);
        initData();

        recNews.setLayoutManager(new LinearLayoutManager(this));
        recNews.setAdapter(new NewsAdapter(listNews,this));

    }
    public void openDetail(News k){
        Intent i = new Intent(this, DescriptionNews.class);
        i.putExtra("nama", k.getNama());
        i.putExtra("deskripsi", k.getDeskripsi());
        i.putExtra("gambar", k.getId_gambar());
        startActivity(i);
    }
    private void initData(){
        this.listNews = new ArrayList<>();
        listNews.add(new News("BNI-ITB Virtual Ultra Marathon Pelari Tempuh 100KM Kurang dari 12 Jam",
                "Kali ini, BNI, Yayasan Solidarity Forever dan Institut Teknologi Bandung (ITB) bekerja sama dalam mewujudkan BNI-ITB Virtual Ultra Marathon 2020, yang diikuti oleh lebih dari 5.000 pelari.",
                "Tak lekang digerus Pandemi Covid-19, PT Bank Negara Indonesia (Persero) Tbk (BNI) melanjutkan dukungannya terhadap lomba lari marathon. Kali ini, BNI, Yayasan Solidarity Forever dan Institut Teknologi Bandung (ITB) bekerja sama dalam mewujudkan BNI-ITB Virtual Ultra Marathon 2020, yang diikuti oleh lebih dari 5.000 pelari. Ada pun keunikan lomba yang tahun ini bertema Run of the Century tersebut adalah para peserta dapat menentukan rute mereka sendiri dengan aplikasi Strava. Perhelatan BNI-ITB Virtual Ultra Marathon ini juga memiliki tujuan untuk memperingati ulang tahun ITB yang ke-100, mengkampanyekan pola hidup sehat melalui olahraga lari, serta mempererat solidaritas alumni ITB. Di Jakarta, Sabtu (12 Desember 2020), Direktur Hubungan Kelembagaan BNI Sis Apik Wijayanto mengatakan, mengingat pandemi Covid-19 yang belum usai, lomba marathon tahun 2020 ini dilaksanakan secara virtual. Hal ini sebagai antisipasi keterbatasan pengumpulan massa. \"Berkat kemampuan teknologi yang ada, para peserta dapat berlari dari mana saja selama rentang waktu yang ditentukan. Ajang yang terdiri dari 3 kategori ini dilakukan secara relay,\" ujar Sis Apik. Pertama dilakukan oleh 2 pelari relay, 4 pelari relay, dan 10 pelari relay, yang dilakukan dengan cara menggabungkan jarak lari peserta hingga terkumpul menjadi 100 km jarak tempuh. Kategori 10 K khusus disediakan bagi peserta alumni ITB. Sedangkan dua kategori lain terbuka bagi masyarakat umum, yakni kategori relay 2 dan relay 4. \"Pencapaian target peserta itu antara lain didasarkan minat besar peserta BNI-ITB Virtual Ultra Marathon. Mereka menikmati ajang ini bukan sekadar moment bernostalgia, melainkan sekaligus menyehatkan lewat aktivitas olahraga,\" ujar Sis Apik\n",
                R.drawable.bni));
        listNews.add(new News("Menoreh Trail Run Donasi Untuk Sekolah di Desa Ngargogondo Borobudur",
                "Menoreh Trail Run Charity 2019 (MTR) sukses digelar pada Minggu (29/9) di Balkondes Ngargogondo Borobudur Kabupaten Magelang. ",
                "Menoreh Trail Run Charity 2019 (MTR) sukses digelar pada Minggu (29/9) di Balkondes Ngargogondo Borobudur Kabupaten Magelang. Diikuti 500 peserta, kegiatan tersebut juga bertujuan untuk amal, yaitu membantu peningkatan kualitas sarana pendidikan untuk tiga sekolah di Desa Ngargogondo, Kecamatan Borobudur, Magelang. \"Ketiga sekolah tersebut adalah TK/RA Muslimat NU, MI Maarif dan SD Negeri Ngargogondo,\" ucap Ketua Panitia Menoreh Trail Run Charity 2019 (MTR) Sulus Arwani. Kegiatan tersebut merupakan kerjasama komunitas Long Run Rangers dengan CBT Balkondes. Long Run Rangers adalah komunitas pelari dari berbagai kota di Indonesia. Mereka hanya melakukan kegiatan lari bersama untuk kegiatan amal. MTR mengambil lokasi start dan finish di Balkondes Ngargogondo. Tiga kategori menjadi pilihan peserta lari lintas alam dengan rute melewati Pegunungan Menoreh, yaitu 25, 10 dan 5 kilometer. Peserta hanya dibatasi 500 orang yang berasal dari para pelari berpengalaman, lintas alam, juga pemula yang datang dari seluruh Indonesia. Direktur PT Manajemen CBT Nusantara (MCN) Jatmika Budi Santoso, yang membawahi 20 Balkondes di Kecamatan Borobudur, mengatakan, kegiatan tersebut secara tidak langsung juga memperkenalkan potensi pariwisata Borobudur. \"Pemerintah akan menggelontorkan dana 2,1 trilyun Rupiah, karena Borobudur menjadi salah satu destinasi super prioritas. Hal tersebut disebutkan saat kunjungan Presiden ke Borobudur kemarin,\" ungkap Jatmika.\n",
                R.drawable.menoreh));
        listNews.add(new News("Memperkenalkan Situs Sangiran Melalui SangiRun: 25K Night Trail Run 2021",
                "Kementerian Pendidikan, Kebudayaan, Riset dan Teknologi melalui Direktorat Jenderal Kebudayaan menggelar 'SangiRun: 25K Night Trail Run' di wilayah Situs Sangiran, Jawa Tengah. Ajang lari sepanjang 25 kilometer akan berlangsung selama tiga hari, 19-21 November 2021. ",
                "Kementerian Pendidikan, Kebudayaan, Riset dan Teknologi melalui Direktorat Jenderal Kebudayaan menggelar 'SangiRun: 25K Night Trail Run' di wilayah Situs Sangiran, Jawa Tengah. Ajang lari sepanjang 25 kilometer akan berlangsung selama tiga hari, 19-21 November 2021. Ajang ini digelar atas kerja sama dengan Balai Pelestarian Situs Manusia Purba (BPSMP) Sangiran, Pemerintah Kabupaten Sragen, dan Pemerintah Kabupaten Karang Anyar serta Kelompok Komunitas Luar Kotak. SangiRun: 25K Night Trail Run diselenggarakan untuk memperingati 25 tahun ditetapkannya Situs Cagar Budaya Sangiran sebagai salah satu warisan dunia oleh UNESCO. Badan PBB itu menetapkan Situs Sangiran sebagai Warisan Budaya Dunia Nomor 593 pada 1996 dengan nama \"The Sangiran Early Man Site.\" Direktur Jenderal Kebudayaan, Kemendikbudristek, Hilmar Farid mengatakan kegiatan ini bukan hanya sekadar lomba lari namun juga usaha mendorong agar situs Sangiran semakin dikenal masyarakat luas dan dapat memberi manfaat bagi masyarakat sekitar Situs Sangiran di Karanganyar dan Sragen, Jawa Tengah. Ditambahkan, 'SangiRun: 25K Night Trail Run' digelar selain untuk memperlihatkan kemampuan manusia dalam beradaptasi terhadap lingkungan, juga untuk memadukan kerjasama antarinstansi pemerintah untuk mendukung kesejahteraan masyarakat Sangiran. \"Narasi yang coba dibangun dalam kegiatan ini adalah untuk memperlihatkan kehidupan masa lampau di Sangiran sebagai sumber pengetahuan kita dan untuk masa kini. Diharapkan situs-situs di Sangiran dapat terus dipelihara dan juga memberi manfaat bagi masyarakat Sangiran dan arena wisata budaya bagi masyarakat luas serta dunia ilmu pengetahuan,\" jelas Hilmar. \"Selain itu kegiatan ini juga melibatkan masyarakat sekitar dengan program Desa Pemajuan Kebudayaan. Masyarakat di sekitar Sangiran melakukan temukenali dan rencana aksi dalam bentuk Pasar Budaya,\" tambahnya. Di sisi lain, Ketua Panitia SangiRun:25K Night Trail 2021, Andre Donas mengatakan ajang lari malam ini akan dihiasi dengan instalasi cahaya, forest video mapping dan ornamen yang menggambarkan evolusi manusia purba. Pada lintasan lari juga akan diterangi oleh nyala obor dengan peserta sekitar 100 pelari yang akan dilepas secara bertahap sesuai dengan protokol kesehatan sehingga tetap terjaga jarak antarpeserta lomba. Dijelasnya, kegiatan ini akan melibatkan para selebriti dan influencer melalui akun instagram sangirun.official seperti komedian Miing dari Bagito Grup dan artis Donna Agnesia. \"Kegiatan ini melibatkan masyarakat Sangiran yang memproduksi kerajinan tangan berupa cindera mata batu sangir, anyaman tikar, kerajinan tangan dari batok kelapa,anyaman plastik daur ulang, kerajianan akar bambu, tenun dan batik sebagai produksi industri rumahan masyarakat Sangiran,” kata Andre.",
                R.drawable.sangiran));
        listNews.add(new News("Satu Kata Peduli Gelar Charity Run Untuk Bantu SLB Mutiara Bangsa Patean",
                "Terletak di desa Patean Sukorejo, Kabupaten Kendal. Dengan sedikit melewati jalan berbatu dari jalan raya, di sinilah Sekolah Luar Biasa (SLB) Mutiara Bangsa menampung 42 anak spesial.",
                "Terletak di desa Patean Sukorejo, Kabupaten Kendal. Dengan sedikit melewati jalan berbatu dari jalan raya, di sinilah Sekolah Luar Biasa (SLB) Mutiara Bangsa menampung 42 anak spesial. Ketua Yayasan Mutiara Bangsa, Nina Dewi Nurchipayana mengatakan, keadaan rumah kontrakan yang sangat sederhana sebagai tempat belajar mereka, tempat sederhana untuk membatik, asrama sederhana untuk tinggal beberapa anak, harus pindah di bulan Oktober ini. Dijelaskan, tidak jauh dari sana tanah seluas 2.000 m2 sudah siap dengan konsep alamnya sebagai gantinya. Namun kendala biaya untuk pembangunan menjadi masalah utama mereka saat ini. \"Ini adalah pekerjaan kita bersama. Mutiara Bangsa adalah rumah bagi anak berkebutuhan khusus. Kalian anak-anak yang spesial,\" ujar Nina, Sabtu (1/8) Sementara itu Marcelli selaku Kordinator Satu Kata Peduli mengatakan, dirinya mendukung kegiatan dari Mutiara Bangsa. Kepedulian kepada anak-anak di daerah ini, agar bisa terus sekolah itu juga menjadi harapannya. Dirinya mengungkapkan, anak- anak yang di sana sangat bersemangat untuk belajar, beberapa sudah sangat mandiri. Bahkan tercatat beberapa anak berprestasi tingkat nasional dalam berolahraga. Tercatat, ada 3 atlet renang yang dihasilkan oleh SLB Mutiara Bangsa, 2 diantaranya akan mewakili Kabupaten Kendal di lomba nasional. \"Anak-anak ini membutuhkan bantuan kita, untuk nantinya tetap bisa bersekolah. Saya suka dengan program Mutiara Bangsa ini, karena punya misi untuk memandirikan,\" ungkapnya. Atas keadaan itulah, Marcelli bersama teman-teman yang tergabung dalam Satu Kata Peduli ingin sekali mengadakan suatu charity run yang nantinya akan membantu meringankan biaya pembangunan SLB tersebut. \"Dengan segala keterbatasan yang ada, tetaplah berdampak. Baik untuk keluarga, untuk Indonesia dan untuk masyarakat di sekitar kita. Maka hidup yang hanya sekali ini, marilah kita berusaha jadi yang berarti,\" imbuhnya. Rencananya, Charity Run akan dilakukan pada tanggal 16-17 Agustus 2020 nanti. Menempuh jarak 75 kilometer, dari Semarang  menuju Sukorejo, Kendal, yang melibatkan 12 pelari dari 6 komunitas. \"Tujuan yang sama yaitu mengumpulkan donasi yang akan digunakan untuk membantu meringankan biaya pembangunan SLB Mutiara Bangsa,\" pungkas Marcelli. \n",
                R.drawable.satukata));
        listNews.add(new News("Borobudur Marathon 2021: 68 Tahun, 2 Kali Kena Covid-19, Finis 21 Km",
                "Jatuh Cinta kepada Lari dan Borobudur Marathon Emil Bachtiar Moerad harus mengakui sulitnya mencari partner latihan karena terbentur usianya. ",
                "Tanpa berolahraga, hidup Emil Bachtiar Moerad terasa hampa. Begitulah adanya. Sejak pensiun di usia 65 tahun, dia tak ingin tinggal diam menikmati masa tuanya. Sebenarnya, rasa cinta Emil terhadap olahraga sudah tertanam sejak lama. Awalnya, dia lebih suka dengan tenis lapangan. \"Tetapi, ada beberapa kejadian yang membuat teman meninggal dunia di lapangan. Akhirnya, saya dilarang main tenis sama istri,\" kata Emil kepada Kompas.com, Minggu (28/11/2021). \"Sejak saat itu atau sejak pensiun, saya mencari olahraga lain. Pernah bersepeda, tapi enggak enak.\" \"Yang paling gampang olahraga adalah lari. Jadi beli sepatu pakai celana pendek, ya sudah lari,\" jelas dia.\u000BEmil mengakui, kali pertama dia ikut berlari adalah pada tahun 2018, atau tiga tahun lalu. Jatuh Cinta kepada Lari dan Borobudur Marathon Emil Bachtiar Moerad harus mengakui sulitnya mencari partner latihan karena terbentur usianya. Tidak banyak komunitas lari yang berisi manusia \"berkepala\" enam. Di sisi lain, tenaganya tentu sangat berbeda dengan pelari-pelari yang jauh lebih muda darinya.  Baca juga: Tilik Candi Borobudur Marathon 2021: Pelari Asal Pontianak Jadi Raja Namun demikian, cinta terhadap olahraga lari tidak membuat patah semangat. Terlebih, cinta memang lebih nikmat untuk dinikmati sendiri. Sejak rutin latihan mulai tahun 2018, dia mulai mencoba mengikuti event-event lomba lari. \"Spesialisasi saya sejak awal memang di half marathon atau 21 km,\" jelasnya. Pada tahun 2019, lanjutnya, kali pertama turut berpartisipasi di Borobudur Marathon. Dia menjadi satu dari 10.000 lebih peserta yang terdaftar saat itu. \"Memang ada daya tarik sendiri untuk kembali ke Magelang,\" ujar dia. Baca juga: Borobudur Marathon 2021: Ganjar Pranowo Ikut Lari Tilik Candi Kalimat itu menjadi alasan dia turut kembali berpartisipasi di Borobudur Marathon, baik pada tahun ini dan tahun depannya lagi. Di ajang Tilik Candi Borobudur Marathon 2021, dia sudah siap untuk melahap 21 km. \"Karena sudah terbiasa latihan, saya tidak ada latihan khusus,\" terangnya. Meski usianya sudah 68 tahun dan pernah terpapar Covid-19 dua kali, dia mampu menjadi finisher 21 km Tilik Candi Borobudur Marathon 2021. \"Saya tadi finis 3 jam 3 menit. Lumayan untuk seusia saya ya,\" kata dia sembari tersenyum. Baca juga: Borobudur Marathon 2021: 128 Pelari Dilepas, Sejarah Tercipta \"Saya juga dapat medali, kan COT (cut off time/batas waktu)-nya 4 jam,\" jelas dia.",
                R.drawable.borobudur));
    }
}